//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleWebCenterExporter.Tests.Services {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceFile {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceFile() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OracleWebCenterExporter.Tests.Services.ResourceFile", typeof(ResourceFile).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;LocalData&quot;: {
        ///    &quot;IdcService&quot;: &quot;SS_GET_SITE_REPORT&quot;,
        ///    &quot;IsJson&quot;: &quot;1&quot;,
        ///    &quot;IsQueryObjectPersistent&quot;: &quot;&quot;,
        ///    &quot;UseForwardOnlyCursor&quot;: &quot;&quot;,
        ///    &quot;changedMonikers&quot;: &quot;&quot;,
        ///    &quot;changedSubjects&quot;: &quot;&quot;,
        ///    &quot;copyAborted&quot;: &quot;0&quot;,
        ///    &quot;dDocName&quot;: &quot;SS_PROJECT_1000026&quot;,
        ///    &quot;dUser&quot;: &quot;username&quot;,
        ///    &quot;dataSource&quot;: &quot;SSLatestReleasedWebsiteDocsDataSource&quot;,
        ///    &quot;idcToken&quot;: &quot;1497473254989:4A7AA25F06171D5FB47760A18ED2E021&quot;,
        ///    &quot;localizedForResponse&quot;: &quot;1&quot;,
        ///    &quot;nextRow&quot;: &quot;5062&quot;,
        ///    &quot;orderClause&quot;: &quot;&quot;,
        ///    &quot;r [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SiteReportMetadataJson {
            get {
                return ResourceManager.GetString("SiteReportMetadataJson", resourceCulture);
            }
        }
    }
}
