//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleWebCenterExporter.DocInfoSvc {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.stellent.com/DocInfo/", ConfigurationName="DocInfoSvc.DocInfoSoap")]
    internal interface DocInfoSoap {
        
        // CODEGEN: Parameter 'extraProps' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.stellent.com/DocInfo/", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        OracleWebCenterExporter.DocInfoSvc.DocInfoByIDResponse DocInfoByID(OracleWebCenterExporter.DocInfoSvc.DocInfoByIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.stellent.com/DocInfo/", ReplyAction="*")]
        System.Threading.Tasks.Task<OracleWebCenterExporter.DocInfoSvc.DocInfoByIDResponse> DocInfoByIDAsync(OracleWebCenterExporter.DocInfoSvc.DocInfoByIDRequest request);
        
        // CODEGEN: Parameter 'extraProps' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.stellent.com/DocInfo/", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        OracleWebCenterExporter.DocInfoSvc.DocInfoByNameResponse DocInfoByName(OracleWebCenterExporter.DocInfoSvc.DocInfoByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.stellent.com/DocInfo/", ReplyAction="*")]
        System.Threading.Tasks.Task<OracleWebCenterExporter.DocInfoSvc.DocInfoByNameResponse> DocInfoByNameAsync(OracleWebCenterExporter.DocInfoSvc.DocInfoByNameRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.stellent.com/DocInfo/")]
    public partial class IdcProperty : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.stellent.com/DocInfo/")]
    public partial class DocInfoByNameResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ContentInfo[] contentInfoField;
        
        private Revisions[] revisionsField;
        
        private WorkflowInfo[] workflowInfoField;
        
        private StatusInfo statusInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ContentInfo", Order=0)]
        public ContentInfo[] ContentInfo {
            get {
                return this.contentInfoField;
            }
            set {
                this.contentInfoField = value;
                this.RaisePropertyChanged("ContentInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Revisions", Order=1)]
        public Revisions[] Revisions {
            get {
                return this.revisionsField;
            }
            set {
                this.revisionsField = value;
                this.RaisePropertyChanged("Revisions");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("WorkflowInfo", Order=2)]
        public WorkflowInfo[] WorkflowInfo {
            get {
                return this.workflowInfoField;
            }
            set {
                this.workflowInfoField = value;
                this.RaisePropertyChanged("WorkflowInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public StatusInfo StatusInfo {
            get {
                return this.statusInfoField;
            }
            set {
                this.statusInfoField = value;
                this.RaisePropertyChanged("StatusInfo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.stellent.com/DocInfo/")]
    public partial class ContentInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string dDocNameField;
        
        private string dDocTitleField;
        
        private string dDocTypeField;
        
        private string dDocAuthorField;
        
        private string dSecurityGroupField;
        
        private string dDocAccountField;
        
        private int dIDField;
        
        private bool dIDFieldSpecified;
        
        private int dRevClassIDField;
        
        private bool dRevClassIDFieldSpecified;
        
        private int dRevisionIDField;
        
        private bool dRevisionIDFieldSpecified;
        
        private string dRevLabelField;
        
        private bool dIsCheckedOutField;
        
        private bool dIsCheckedOutFieldSpecified;
        
        private string dCheckoutUserField;
        
        private string dCreateDateField;
        
        private string dInDateField;
        
        private string dOutDateField;
        
        private string dStatusField;
        
        private string dReleaseStateField;
        
        private string dFlag1Field;
        
        private string dWebExtensionField;
        
        private string dProcessingStateField;
        
        private string dMessageField;
        
        private string dReleaseDateField;
        
        private string dRendition1Field;
        
        private string dRendition2Field;
        
        private string dIndexerStateField;
        
        private string dPublishTypeField;
        
        private string dPublishStateField;
        
        private int dDocIDField;
        
        private bool dDocIDFieldSpecified;
        
        private bool dIsPrimaryField;
        
        private bool dIsPrimaryFieldSpecified;
        
        private bool dIsWebFormatField;
        
        private bool dIsWebFormatFieldSpecified;
        
        private string dLocationField;
        
        private string dOriginalNameField;
        
        private string dFormatField;
        
        private string dExtensionField;
        
        private int dFileSizeField;
        
        private bool dFileSizeFieldSpecified;
        
        private IdcProperty[] customDocMetaDataField;
        
        private string urlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string dDocName {
            get {
                return this.dDocNameField;
            }
            set {
                this.dDocNameField = value;
                this.RaisePropertyChanged("dDocName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string dDocTitle {
            get {
                return this.dDocTitleField;
            }
            set {
                this.dDocTitleField = value;
                this.RaisePropertyChanged("dDocTitle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string dDocType {
            get {
                return this.dDocTypeField;
            }
            set {
                this.dDocTypeField = value;
                this.RaisePropertyChanged("dDocType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string dDocAuthor {
            get {
                return this.dDocAuthorField;
            }
            set {
                this.dDocAuthorField = value;
                this.RaisePropertyChanged("dDocAuthor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string dSecurityGroup {
            get {
                return this.dSecurityGroupField;
            }
            set {
                this.dSecurityGroupField = value;
                this.RaisePropertyChanged("dSecurityGroup");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string dDocAccount {
            get {
                return this.dDocAccountField;
            }
            set {
                this.dDocAccountField = value;
                this.RaisePropertyChanged("dDocAccount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int dID {
            get {
                return this.dIDField;
            }
            set {
                this.dIDField = value;
                this.RaisePropertyChanged("dID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dIDSpecified {
            get {
                return this.dIDFieldSpecified;
            }
            set {
                this.dIDFieldSpecified = value;
                this.RaisePropertyChanged("dIDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int dRevClassID {
            get {
                return this.dRevClassIDField;
            }
            set {
                this.dRevClassIDField = value;
                this.RaisePropertyChanged("dRevClassID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dRevClassIDSpecified {
            get {
                return this.dRevClassIDFieldSpecified;
            }
            set {
                this.dRevClassIDFieldSpecified = value;
                this.RaisePropertyChanged("dRevClassIDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int dRevisionID {
            get {
                return this.dRevisionIDField;
            }
            set {
                this.dRevisionIDField = value;
                this.RaisePropertyChanged("dRevisionID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dRevisionIDSpecified {
            get {
                return this.dRevisionIDFieldSpecified;
            }
            set {
                this.dRevisionIDFieldSpecified = value;
                this.RaisePropertyChanged("dRevisionIDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string dRevLabel {
            get {
                return this.dRevLabelField;
            }
            set {
                this.dRevLabelField = value;
                this.RaisePropertyChanged("dRevLabel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public bool dIsCheckedOut {
            get {
                return this.dIsCheckedOutField;
            }
            set {
                this.dIsCheckedOutField = value;
                this.RaisePropertyChanged("dIsCheckedOut");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dIsCheckedOutSpecified {
            get {
                return this.dIsCheckedOutFieldSpecified;
            }
            set {
                this.dIsCheckedOutFieldSpecified = value;
                this.RaisePropertyChanged("dIsCheckedOutSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string dCheckoutUser {
            get {
                return this.dCheckoutUserField;
            }
            set {
                this.dCheckoutUserField = value;
                this.RaisePropertyChanged("dCheckoutUser");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string dCreateDate {
            get {
                return this.dCreateDateField;
            }
            set {
                this.dCreateDateField = value;
                this.RaisePropertyChanged("dCreateDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string dInDate {
            get {
                return this.dInDateField;
            }
            set {
                this.dInDateField = value;
                this.RaisePropertyChanged("dInDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string dOutDate {
            get {
                return this.dOutDateField;
            }
            set {
                this.dOutDateField = value;
                this.RaisePropertyChanged("dOutDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string dStatus {
            get {
                return this.dStatusField;
            }
            set {
                this.dStatusField = value;
                this.RaisePropertyChanged("dStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string dReleaseState {
            get {
                return this.dReleaseStateField;
            }
            set {
                this.dReleaseStateField = value;
                this.RaisePropertyChanged("dReleaseState");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string dFlag1 {
            get {
                return this.dFlag1Field;
            }
            set {
                this.dFlag1Field = value;
                this.RaisePropertyChanged("dFlag1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string dWebExtension {
            get {
                return this.dWebExtensionField;
            }
            set {
                this.dWebExtensionField = value;
                this.RaisePropertyChanged("dWebExtension");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string dProcessingState {
            get {
                return this.dProcessingStateField;
            }
            set {
                this.dProcessingStateField = value;
                this.RaisePropertyChanged("dProcessingState");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string dMessage {
            get {
                return this.dMessageField;
            }
            set {
                this.dMessageField = value;
                this.RaisePropertyChanged("dMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string dReleaseDate {
            get {
                return this.dReleaseDateField;
            }
            set {
                this.dReleaseDateField = value;
                this.RaisePropertyChanged("dReleaseDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string dRendition1 {
            get {
                return this.dRendition1Field;
            }
            set {
                this.dRendition1Field = value;
                this.RaisePropertyChanged("dRendition1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string dRendition2 {
            get {
                return this.dRendition2Field;
            }
            set {
                this.dRendition2Field = value;
                this.RaisePropertyChanged("dRendition2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string dIndexerState {
            get {
                return this.dIndexerStateField;
            }
            set {
                this.dIndexerStateField = value;
                this.RaisePropertyChanged("dIndexerState");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string dPublishType {
            get {
                return this.dPublishTypeField;
            }
            set {
                this.dPublishTypeField = value;
                this.RaisePropertyChanged("dPublishType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string dPublishState {
            get {
                return this.dPublishStateField;
            }
            set {
                this.dPublishStateField = value;
                this.RaisePropertyChanged("dPublishState");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public int dDocID {
            get {
                return this.dDocIDField;
            }
            set {
                this.dDocIDField = value;
                this.RaisePropertyChanged("dDocID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dDocIDSpecified {
            get {
                return this.dDocIDFieldSpecified;
            }
            set {
                this.dDocIDFieldSpecified = value;
                this.RaisePropertyChanged("dDocIDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public bool dIsPrimary {
            get {
                return this.dIsPrimaryField;
            }
            set {
                this.dIsPrimaryField = value;
                this.RaisePropertyChanged("dIsPrimary");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dIsPrimarySpecified {
            get {
                return this.dIsPrimaryFieldSpecified;
            }
            set {
                this.dIsPrimaryFieldSpecified = value;
                this.RaisePropertyChanged("dIsPrimarySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public bool dIsWebFormat {
            get {
                return this.dIsWebFormatField;
            }
            set {
                this.dIsWebFormatField = value;
                this.RaisePropertyChanged("dIsWebFormat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dIsWebFormatSpecified {
            get {
                return this.dIsWebFormatFieldSpecified;
            }
            set {
                this.dIsWebFormatFieldSpecified = value;
                this.RaisePropertyChanged("dIsWebFormatSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public string dLocation {
            get {
                return this.dLocationField;
            }
            set {
                this.dLocationField = value;
                this.RaisePropertyChanged("dLocation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public string dOriginalName {
            get {
                return this.dOriginalNameField;
            }
            set {
                this.dOriginalNameField = value;
                this.RaisePropertyChanged("dOriginalName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public string dFormat {
            get {
                return this.dFormatField;
            }
            set {
                this.dFormatField = value;
                this.RaisePropertyChanged("dFormat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public string dExtension {
            get {
                return this.dExtensionField;
            }
            set {
                this.dExtensionField = value;
                this.RaisePropertyChanged("dExtension");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public int dFileSize {
            get {
                return this.dFileSizeField;
            }
            set {
                this.dFileSizeField = value;
                this.RaisePropertyChanged("dFileSize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dFileSizeSpecified {
            get {
                return this.dFileSizeFieldSpecified;
            }
            set {
                this.dFileSizeFieldSpecified = value;
                this.RaisePropertyChanged("dFileSizeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=35)]
        [System.Xml.Serialization.XmlArrayItemAttribute("property", IsNullable=false)]
        public IdcProperty[] CustomDocMetaData {
            get {
                return this.customDocMetaDataField;
            }
            set {
                this.customDocMetaDataField = value;
                this.RaisePropertyChanged("CustomDocMetaData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=36)]
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
                this.RaisePropertyChanged("url");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.stellent.com/DocInfo/")]
    public partial class Revisions : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string dFormatField;
        
        private string dInDateField;
        
        private string dOutDateField;
        
        private string dStatusField;
        
        private string dProcessingStateField;
        
        private string dRevLabelField;
        
        private int dIDField;
        
        private bool dIDFieldSpecified;
        
        private string dDocNameField;
        
        private int dRevisionIDField;
        
        private bool dRevisionIDFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string dFormat {
            get {
                return this.dFormatField;
            }
            set {
                this.dFormatField = value;
                this.RaisePropertyChanged("dFormat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string dInDate {
            get {
                return this.dInDateField;
            }
            set {
                this.dInDateField = value;
                this.RaisePropertyChanged("dInDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string dOutDate {
            get {
                return this.dOutDateField;
            }
            set {
                this.dOutDateField = value;
                this.RaisePropertyChanged("dOutDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string dStatus {
            get {
                return this.dStatusField;
            }
            set {
                this.dStatusField = value;
                this.RaisePropertyChanged("dStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string dProcessingState {
            get {
                return this.dProcessingStateField;
            }
            set {
                this.dProcessingStateField = value;
                this.RaisePropertyChanged("dProcessingState");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string dRevLabel {
            get {
                return this.dRevLabelField;
            }
            set {
                this.dRevLabelField = value;
                this.RaisePropertyChanged("dRevLabel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int dID {
            get {
                return this.dIDField;
            }
            set {
                this.dIDField = value;
                this.RaisePropertyChanged("dID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dIDSpecified {
            get {
                return this.dIDFieldSpecified;
            }
            set {
                this.dIDFieldSpecified = value;
                this.RaisePropertyChanged("dIDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string dDocName {
            get {
                return this.dDocNameField;
            }
            set {
                this.dDocNameField = value;
                this.RaisePropertyChanged("dDocName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int dRevisionID {
            get {
                return this.dRevisionIDField;
            }
            set {
                this.dRevisionIDField = value;
                this.RaisePropertyChanged("dRevisionID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dRevisionIDSpecified {
            get {
                return this.dRevisionIDFieldSpecified;
            }
            set {
                this.dRevisionIDFieldSpecified = value;
                this.RaisePropertyChanged("dRevisionIDSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.stellent.com/DocInfo/")]
    public partial class WorkflowInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int dWfIDField;
        
        private bool dWfIDFieldSpecified;
        
        private string dDocNameField;
        
        private string dWfDocStateField;
        
        private string dWfComputedField;
        
        private int dWfCurrentStepIDField;
        
        private bool dWfCurrentStepIDFieldSpecified;
        
        private string dWfDirectoryField;
        
        private string dClbraNameField;
        
        private string dWfNameField;
        
        private string dWfDescriptionField;
        
        private string dCompletionDateField;
        
        private string dSecurityGroupField;
        
        private string dWfStatusField;
        
        private string dWfTypeField;
        
        private string dProjectIDField;
        
        private bool dIsCollaborationField;
        
        private bool dIsCollaborationFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int dWfID {
            get {
                return this.dWfIDField;
            }
            set {
                this.dWfIDField = value;
                this.RaisePropertyChanged("dWfID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dWfIDSpecified {
            get {
                return this.dWfIDFieldSpecified;
            }
            set {
                this.dWfIDFieldSpecified = value;
                this.RaisePropertyChanged("dWfIDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string dDocName {
            get {
                return this.dDocNameField;
            }
            set {
                this.dDocNameField = value;
                this.RaisePropertyChanged("dDocName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string dWfDocState {
            get {
                return this.dWfDocStateField;
            }
            set {
                this.dWfDocStateField = value;
                this.RaisePropertyChanged("dWfDocState");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string dWfComputed {
            get {
                return this.dWfComputedField;
            }
            set {
                this.dWfComputedField = value;
                this.RaisePropertyChanged("dWfComputed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int dWfCurrentStepID {
            get {
                return this.dWfCurrentStepIDField;
            }
            set {
                this.dWfCurrentStepIDField = value;
                this.RaisePropertyChanged("dWfCurrentStepID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dWfCurrentStepIDSpecified {
            get {
                return this.dWfCurrentStepIDFieldSpecified;
            }
            set {
                this.dWfCurrentStepIDFieldSpecified = value;
                this.RaisePropertyChanged("dWfCurrentStepIDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string dWfDirectory {
            get {
                return this.dWfDirectoryField;
            }
            set {
                this.dWfDirectoryField = value;
                this.RaisePropertyChanged("dWfDirectory");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string dClbraName {
            get {
                return this.dClbraNameField;
            }
            set {
                this.dClbraNameField = value;
                this.RaisePropertyChanged("dClbraName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string dWfName {
            get {
                return this.dWfNameField;
            }
            set {
                this.dWfNameField = value;
                this.RaisePropertyChanged("dWfName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string dWfDescription {
            get {
                return this.dWfDescriptionField;
            }
            set {
                this.dWfDescriptionField = value;
                this.RaisePropertyChanged("dWfDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string dCompletionDate {
            get {
                return this.dCompletionDateField;
            }
            set {
                this.dCompletionDateField = value;
                this.RaisePropertyChanged("dCompletionDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string dSecurityGroup {
            get {
                return this.dSecurityGroupField;
            }
            set {
                this.dSecurityGroupField = value;
                this.RaisePropertyChanged("dSecurityGroup");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string dWfStatus {
            get {
                return this.dWfStatusField;
            }
            set {
                this.dWfStatusField = value;
                this.RaisePropertyChanged("dWfStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string dWfType {
            get {
                return this.dWfTypeField;
            }
            set {
                this.dWfTypeField = value;
                this.RaisePropertyChanged("dWfType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string dProjectID {
            get {
                return this.dProjectIDField;
            }
            set {
                this.dProjectIDField = value;
                this.RaisePropertyChanged("dProjectID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public bool dIsCollaboration {
            get {
                return this.dIsCollaborationField;
            }
            set {
                this.dIsCollaborationField = value;
                this.RaisePropertyChanged("dIsCollaboration");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dIsCollaborationSpecified {
            get {
                return this.dIsCollaborationFieldSpecified;
            }
            set {
                this.dIsCollaborationFieldSpecified = value;
                this.RaisePropertyChanged("dIsCollaborationSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.stellent.com/DocInfo/")]
    public partial class StatusInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int statusCodeField;
        
        private bool statusCodeFieldSpecified;
        
        private string statusMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int statusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
                this.RaisePropertyChanged("statusCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusCodeSpecified {
            get {
                return this.statusCodeFieldSpecified;
            }
            set {
                this.statusCodeFieldSpecified = value;
                this.RaisePropertyChanged("statusCodeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string statusMessage {
            get {
                return this.statusMessageField;
            }
            set {
                this.statusMessageField = value;
                this.RaisePropertyChanged("statusMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.stellent.com/DocInfo/")]
    public partial class DocInfoByIDResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ContentInfo[] contentInfoField;
        
        private Revisions[] revisionsField;
        
        private WorkflowInfo[] workflowInfoField;
        
        private StatusInfo statusInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ContentInfo", Order=0)]
        public ContentInfo[] ContentInfo {
            get {
                return this.contentInfoField;
            }
            set {
                this.contentInfoField = value;
                this.RaisePropertyChanged("ContentInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Revisions", Order=1)]
        public Revisions[] Revisions {
            get {
                return this.revisionsField;
            }
            set {
                this.revisionsField = value;
                this.RaisePropertyChanged("Revisions");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("WorkflowInfo", Order=2)]
        public WorkflowInfo[] WorkflowInfo {
            get {
                return this.workflowInfoField;
            }
            set {
                this.workflowInfoField = value;
                this.RaisePropertyChanged("WorkflowInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public StatusInfo StatusInfo {
            get {
                return this.statusInfoField;
            }
            set {
                this.statusInfoField = value;
                this.RaisePropertyChanged("StatusInfo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DocInfoByID", WrapperNamespace="http://www.stellent.com/DocInfo/", IsWrapped=true)]
    internal partial class DocInfoByIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.stellent.com/DocInfo/", Order=0)]
        public int dID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.stellent.com/DocInfo/", Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("property", IsNullable=false)]
        public OracleWebCenterExporter.DocInfoSvc.IdcProperty[] extraProps;
        
        public DocInfoByIDRequest() {
        }
        
        public DocInfoByIDRequest(int dID, OracleWebCenterExporter.DocInfoSvc.IdcProperty[] extraProps) {
            this.dID = dID;
            this.extraProps = extraProps;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DocInfoByIDResponse", WrapperNamespace="http://www.stellent.com/DocInfo/", IsWrapped=true)]
    internal partial class DocInfoByIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.stellent.com/DocInfo/", Order=0)]
        public OracleWebCenterExporter.DocInfoSvc.DocInfoByIDResult DocInfoByIDResult;
        
        public DocInfoByIDResponse() {
        }
        
        public DocInfoByIDResponse(OracleWebCenterExporter.DocInfoSvc.DocInfoByIDResult DocInfoByIDResult) {
            this.DocInfoByIDResult = DocInfoByIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DocInfoByName", WrapperNamespace="http://www.stellent.com/DocInfo/", IsWrapped=true)]
    internal partial class DocInfoByNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.stellent.com/DocInfo/", Order=0)]
        public string dDocName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.stellent.com/DocInfo/", Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("property", IsNullable=false)]
        public OracleWebCenterExporter.DocInfoSvc.IdcProperty[] extraProps;
        
        public DocInfoByNameRequest() {
        }
        
        public DocInfoByNameRequest(string dDocName, OracleWebCenterExporter.DocInfoSvc.IdcProperty[] extraProps) {
            this.dDocName = dDocName;
            this.extraProps = extraProps;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DocInfoByNameResponse", WrapperNamespace="http://www.stellent.com/DocInfo/", IsWrapped=true)]
    internal partial class DocInfoByNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.stellent.com/DocInfo/", Order=0)]
        public OracleWebCenterExporter.DocInfoSvc.DocInfoByNameResult DocInfoByNameResult;
        
        public DocInfoByNameResponse() {
        }
        
        public DocInfoByNameResponse(OracleWebCenterExporter.DocInfoSvc.DocInfoByNameResult DocInfoByNameResult) {
            this.DocInfoByNameResult = DocInfoByNameResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal interface DocInfoSoapChannel : OracleWebCenterExporter.DocInfoSvc.DocInfoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal partial class DocInfoSoapClient : System.ServiceModel.ClientBase<OracleWebCenterExporter.DocInfoSvc.DocInfoSoap>, OracleWebCenterExporter.DocInfoSvc.DocInfoSoap {
        
        public DocInfoSoapClient() {
        }
        
        public DocInfoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DocInfoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DocInfoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DocInfoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OracleWebCenterExporter.DocInfoSvc.DocInfoByIDResponse OracleWebCenterExporter.DocInfoSvc.DocInfoSoap.DocInfoByID(OracleWebCenterExporter.DocInfoSvc.DocInfoByIDRequest request) {
            return base.Channel.DocInfoByID(request);
        }
        
        public OracleWebCenterExporter.DocInfoSvc.DocInfoByIDResult DocInfoByID(int dID, OracleWebCenterExporter.DocInfoSvc.IdcProperty[] extraProps) {
            OracleWebCenterExporter.DocInfoSvc.DocInfoByIDRequest inValue = new OracleWebCenterExporter.DocInfoSvc.DocInfoByIDRequest();
            inValue.dID = dID;
            inValue.extraProps = extraProps;
            OracleWebCenterExporter.DocInfoSvc.DocInfoByIDResponse retVal = ((OracleWebCenterExporter.DocInfoSvc.DocInfoSoap)(this)).DocInfoByID(inValue);
            return retVal.DocInfoByIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OracleWebCenterExporter.DocInfoSvc.DocInfoByIDResponse> OracleWebCenterExporter.DocInfoSvc.DocInfoSoap.DocInfoByIDAsync(OracleWebCenterExporter.DocInfoSvc.DocInfoByIDRequest request) {
            return base.Channel.DocInfoByIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<OracleWebCenterExporter.DocInfoSvc.DocInfoByIDResponse> DocInfoByIDAsync(int dID, OracleWebCenterExporter.DocInfoSvc.IdcProperty[] extraProps) {
            OracleWebCenterExporter.DocInfoSvc.DocInfoByIDRequest inValue = new OracleWebCenterExporter.DocInfoSvc.DocInfoByIDRequest();
            inValue.dID = dID;
            inValue.extraProps = extraProps;
            return ((OracleWebCenterExporter.DocInfoSvc.DocInfoSoap)(this)).DocInfoByIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OracleWebCenterExporter.DocInfoSvc.DocInfoByNameResponse OracleWebCenterExporter.DocInfoSvc.DocInfoSoap.DocInfoByName(OracleWebCenterExporter.DocInfoSvc.DocInfoByNameRequest request) {
            return base.Channel.DocInfoByName(request);
        }
        
        public OracleWebCenterExporter.DocInfoSvc.DocInfoByNameResult DocInfoByName(string dDocName, OracleWebCenterExporter.DocInfoSvc.IdcProperty[] extraProps) {
            OracleWebCenterExporter.DocInfoSvc.DocInfoByNameRequest inValue = new OracleWebCenterExporter.DocInfoSvc.DocInfoByNameRequest();
            inValue.dDocName = dDocName;
            inValue.extraProps = extraProps;
            OracleWebCenterExporter.DocInfoSvc.DocInfoByNameResponse retVal = ((OracleWebCenterExporter.DocInfoSvc.DocInfoSoap)(this)).DocInfoByName(inValue);
            return retVal.DocInfoByNameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OracleWebCenterExporter.DocInfoSvc.DocInfoByNameResponse> OracleWebCenterExporter.DocInfoSvc.DocInfoSoap.DocInfoByNameAsync(OracleWebCenterExporter.DocInfoSvc.DocInfoByNameRequest request) {
            return base.Channel.DocInfoByNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<OracleWebCenterExporter.DocInfoSvc.DocInfoByNameResponse> DocInfoByNameAsync(string dDocName, OracleWebCenterExporter.DocInfoSvc.IdcProperty[] extraProps) {
            OracleWebCenterExporter.DocInfoSvc.DocInfoByNameRequest inValue = new OracleWebCenterExporter.DocInfoSvc.DocInfoByNameRequest();
            inValue.dDocName = dDocName;
            inValue.extraProps = extraProps;
            return ((OracleWebCenterExporter.DocInfoSvc.DocInfoSoap)(this)).DocInfoByNameAsync(inValue);
        }
    }
}
